//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.01 at 10:29:01 AM CEST 
//


package info.rexs.upgrade.upgraders.changelog.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for changedValueKey.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="changedValueKey"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="componentId"/&gt;
 *     &lt;enumeration value="attributeId"/&gt;
 *     &lt;enumeration value="numericId"/&gt;
 *     &lt;enumeration value="valuetype"/&gt;
 *     &lt;enumeration value="unit"/&gt;
 *     &lt;enumeration value="symbol"/&gt;
 *     &lt;enumeration value="range"/&gt;
 *     &lt;enumeration value="enumvalues"/&gt;
 *     &lt;enumeration value="value"/&gt;
 *     &lt;enumeration value="name"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "changedValueKey")
@XmlEnum
public enum ChangedValueKey {

    @XmlEnumValue("componentId")
    COMPONENT_ID("componentId"),
    @XmlEnumValue("attributeId")
    ATTRIBUTE_ID("attributeId"),
    @XmlEnumValue("numericId")
    NUMERIC_ID("numericId"),
    @XmlEnumValue("valuetype")
    VALUETYPE("valuetype"),
    @XmlEnumValue("unit")
    UNIT("unit"),
    @XmlEnumValue("symbol")
    SYMBOL("symbol"),
    @XmlEnumValue("range")
    RANGE("range"),
    @XmlEnumValue("enumvalues")
    ENUMVALUES("enumvalues"),
    @XmlEnumValue("value")
    VALUE("value"),
    @XmlEnumValue("name")
    NAME("name");
    private final String value;

    ChangedValueKey(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChangedValueKey fromValue(String v) {
        for (ChangedValueKey c: ChangedValueKey.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
