//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.08.01 at 10:29:01 AM CEST
//


package info.rexs.upgrade.upgraders.changelog.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="type" use="required" type="{}changeType" /&gt;
 *       &lt;attribute name="componentId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="attributeId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="attributeNumericId" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "mappingChange")
public class MappingChange {

    @XmlAttribute(name = "type", required = true)
    protected ChangeType type;
    @XmlAttribute(name = "componentId", required = true)
    protected String componentId;
    @XmlAttribute(name = "attributeId", required = true)
    protected String attributeId;
    @XmlAttribute(name = "attributeNumericId", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected int attributeNumericId;

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link ChangeType }
     *
     */
    public ChangeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link ChangeType }
     *
     */
    public void setType(ChangeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the componentId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getComponentId() {
        return componentId;
    }

    /**
     * Sets the value of the componentId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setComponentId(String value) {
        this.componentId = value;
    }

    /**
     * Gets the value of the attributeId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAttributeId() {
        return attributeId;
    }

    /**
     * Sets the value of the attributeId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAttributeId(String value) {
        this.attributeId = value;
    }

    /**
     * Gets the value of the attributeNumericId property.
     *
     * @return
     *     possible object is
     *     {@code int}
     *
     */
    public int getAttributeNumericId() {
        return attributeNumericId;
    }

    /**
     * Sets the value of the attributeNumericId property.
     *
     * @param value
     *     allowed object is
     *     {@code int}
     *
     */
    public void setAttributeNumericId(int value) {
        this.attributeNumericId = value;
    }

}
