//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.01 at 10:29:01 AM CEST 
//


package info.rexs.upgrade.upgraders.changelog.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}componentChanges" minOccurs="0"/&gt;
 *         &lt;element ref="{}attributeChanges" minOccurs="0"/&gt;
 *         &lt;element ref="{}mappingChanges" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="fromVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="toVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "componentChanges",
    "attributeChanges",
    "mappingChanges"
})
@XmlRootElement(name = "rexsChangelog")
public class RexsChangelog {

    protected ComponentChanges componentChanges;
    protected AttributeChanges attributeChanges;
    protected MappingChanges mappingChanges;
    @XmlAttribute(name = "fromVersion", required = true)
    protected String fromVersion;
    @XmlAttribute(name = "toVersion", required = true)
    protected String toVersion;

    /**
     * Gets the value of the componentChanges property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentChanges }
     *     
     */
    public ComponentChanges getComponentChanges() {
        return componentChanges;
    }

    /**
     * Sets the value of the componentChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentChanges }
     *     
     */
    public void setComponentChanges(ComponentChanges value) {
        this.componentChanges = value;
    }

    /**
     * Gets the value of the attributeChanges property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeChanges }
     *     
     */
    public AttributeChanges getAttributeChanges() {
        return attributeChanges;
    }

    /**
     * Sets the value of the attributeChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeChanges }
     *     
     */
    public void setAttributeChanges(AttributeChanges value) {
        this.attributeChanges = value;
    }

    /**
     * Gets the value of the mappingChanges property.
     * 
     * @return
     *     possible object is
     *     {@link MappingChanges }
     *     
     */
    public MappingChanges getMappingChanges() {
        return mappingChanges;
    }

    /**
     * Sets the value of the mappingChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingChanges }
     *     
     */
    public void setMappingChanges(MappingChanges value) {
        this.mappingChanges = value;
    }

    /**
     * Gets the value of the fromVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromVersion() {
        return fromVersion;
    }

    /**
     * Sets the value of the fromVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromVersion(String value) {
        this.fromVersion = value;
    }

    /**
     * Gets the value of the toVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToVersion() {
        return toVersion;
    }

    /**
     * Sets the value of the toVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToVersion(String value) {
        this.toVersion = value;
    }

}
